services:
  - type: web
    name: reddit-trends
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    autoDeploy: true
    envVars:
      # DATABASE_URL will be injected from the database below
      - key: DATABASE_URL
        fromDatabase:
          name: reddit-trends-db
          property: connectionString

      # Email (SMTP). Fill real values in Render after deploy; PASS stays secret.
      - key: SMTP_HOST
        value: smtp.sendgrid.net
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: apikey
      - key: SMTP_PASS
        sync: false         # set this secret in the Render dashboard
      - key: FROM_EMAIL
        value: you@yourdomain.com

      # Will update to your live URL after first deploy (ok to keep placeholder now)
      - key: BASE_URL
        value: https://your-app.onrender.com

databases:
  - name: reddit-trends-db
    plan: free
